apiVersion: 1

datasources:
  - name: RadarDB
    type: grafana-postgresql-datasource
    uid: radardb
    url: postgres:5432
    database: radar_db
    user: radar
    secureJsonData:
      password: radar
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
